set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a

set -g mouse on

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

set-option -g status-position top
set -g status-style "fg=white bg=color237"

set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=default,bg=default

set -g window-style 'bg=default'
set -g window-active-style 'bg=default'


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "janoamaral/tokyo-night-tmux"
# tokyo-night-tmux settings

# style
set -g @tokyo-night-tmux_window_id_style dsquare 

# music
set -g @tokyo-night-tmux_show_music 1

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# plugins or settings i no longer use

# battery
# set -g @plugin 'tmux-plugins/tmux-battery'


# catppuccin settings
# set -g @plugin 'catppuccin/tmux'

# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"
#
# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_window_default_text "#W"
#
# set -g @catppuccin_status_modules_right "session date_time battery"
# set -g @catppuccin_status_modules_left "user"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator ""
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"
# set -g @catppuccin_status_background "default"
#
# set -g @catppuccin_date_time_text "%m-%d %H:%M"
#
# set -g @catppuccin_directory_text "#{pane_current_path}"

